### PR TITLE
Allow to change image rotation

### PR DESCRIPTION
**Pull request by simon04**
- [x] migrate to [cropper.js](https://fengyuanchen.github.io/cropperjs/), a cropping tool which supports rotation
- [x] integrate simple input to change image rotation
- [x] send image rotation to backend
- [x] backend: take image rotation into account

Due to the complexity to get a running development backend, help for the fourth item is highly appreciated.

Addresses #17.

### CODE REVIEW

**Comment by danmichaelo** [comment]
Thanks, and sorry I didn't get back to you before! I can fix the backend part, but there are a few more issues that need to be addressed:

- Lossless jpeg cropping can only support rotation angles dividable by 90. The user interface needs to reflect this.. perhaps the input field should be replaced by a dropdown ( 0, 90, 180 and 270 ) when you select lossless?
- The two calls to `jcrop_api.setSelect()` must be ported to cropperjs:
  - In the `$scope.onCropDimChange()` method: When the values in the input fields "Top", "Left", "Width" and "Height" are edited, the crop area should reflect the new values.
  - In `$scope.locateBorder()`:  When we get coordinates from the magic border selector, the crop area should reflect these.

Note: I rebased your branch onto master.

**Comment by simon04** [comment]
Now it was me being busy lately. I addresses the two issues. Please check. :smile: 

Setting `viewMode` to 2 still allows me to set an area outside of the image (tested w/ 45° rotation on a portrait image).

**Comment by danmichaelo** [comment]
Thanks! Fixed a few more issues as you can see (combination of rotation and EXIF orientation was especially "fun").

One issue left is that if you rotate a flat image like [this](https://commons.wikimedia.org/wiki/File:Berlin_-_Schloss_Bellevue2.jpg), a large part of the image will end up outside the canvas, making it quite hard to crop (even when you figure out that you can zoom using the scrool wheel, it's hard). Would it work to have the canvas expand/contract to match the rotated image?

croptool testing 1

**Comment by simon04** [comment]
An approach would be to automatically zoom out using `zoomTo(ration`) with the `ratio = Math.min(getData().height / getContainerData().height, getData().width / getContainerData().width)`.

**Comment by danmichaelo** [comment]
Yeah, I think that could work and it's easy to implement.  In addition, we *could* also make a minium aspect ratio for the canvas, so if that the image is very flat, like the example image above, there would be extra vertical working space on the canvas from the beginning:

extra-space

**Comment by simon04** [comment]
I tried to address both of your suggestions. Hopefully, this PR can be merged eventually. :smile:

**Comment by danmichaelo** [comment]
Thanks, I'll try to do some testing this weekend :)

**Comment by danmichaelo** [comment]
Or next weekend… Used all my "wiki time" this weekend to port updated CS1 templates to no.wiki :)

**Comment by danmichaelo** [comment]
bb4ab8435ded8ed506cd2a5523f3e5b12e40e951 only worked now and then. Reloading the page produced different results every time:

croptool testing 3

Turned out that `element.first().width()` and `element.first().height()` were sometimes zero in initCropper even though `element[0].width` and `element[0].height` were not.. Anyways, I went for a slightly different approach where I fix the container to `width: 60vw; min-height: 30vw`. This way it also scales with the display size.

I struggled quite a bit with an annoying issue where the cropper doesn't initialize with the right dimensions:

croptool testing 4

Adding a zero $timeout to initialize it in the next tick almost removed the issue, but I'm still quite sure I saw it once after adding that, so I'm not convinced it's completely gone.. 

Anyways, the branch is now merged. If you can do some testing it's much appreciated.

**Pull request merged**
