### PR TITLE
Use angular-translate for I18n	

### PR DESCRIPTION
**Pull request by simon04**
Use [angular-translate](https://angular-translate.github.io/) for I18n instead of TsIntuition.

Relates to #28: The `en.json` can be uploaded to Transifex for translation, see http://docs.transifex.com/formats/json/ for the format support.

### CODE REVIEW

**Comment by danmichaelo** [comment]
Cool, thanks. But it would be nice to be able to use TranslateWiki as a translation platform (that was my reason for using Intuition, even though I didn't get around to actually submit CropTool to it :)). Have you checked if there's an easy way to integrate with it? Perhaps generate the JSON from Intuition? Or perhaps use angular-gettext over angular-translate?

**Comment by simon04** [comment]
Hm, I always feel lost on TranslateWiki … However, the JSON format seems to be supported. At least the [MultimediaViewer](https://www.mediawiki.org/wiki/Extension:MultimediaViewer) relies on this combination, see https://git.wikimedia.org/tree/mediawiki%2Fextensions%2FMultimediaViewer/master/i18n

**Comment by danmichaelo** [comment]
Yeah, I find next to no information about how to submit new projects or translation groups.. but they refer to irc a lot, so perhaps I have to go there and ask. Give me some days and I can do some investigation. Unless you beat me at it :)

**Comment by danmichaelo** [comment]
Anyways, I just merge it now. In any case, it's nice to get rid of the inline php.

**Pull request merged**
